### ISSUE TITLE
Refactor Header component to make it more dynamic

### ISSUE THREAD

**Issue by jeafreezy** [gisfest/gisfest-conference-website#29]
Great work on the Header component @vickystickz . I worked on the 404 and 500 pages on my fork and I was trying to move the header component to the layout.tsx, but it's not working as expected.

This is because the header component transition is coupled with the Jumbotron component. Can you make it flexible? Such that It can be moved to the layout file and will be static across the app.

You know we have some more pages to work on, so the header and footer must be in the layout.tsx file and be consistent across the website .

Let me know if you need some clarifications..

Thanks!

**Comment by vickystickz** [comment]
#30 - This PR covers solution to this issue, kindly review 
Note: You can now proceed to add the header component in the layout.tsx #file
