### ISSUE TITLE
Deployment not working - Next MDX

### ISSUE THREAD

**Issue by jeafreezy** [gisfest/gisfest-conference-website#39]
I set up Next MDX following the [documentation](https://nextjs.org/docs/app/building-your-application/configuring/mdx) to use in our content heavy pages e.g call for speakers.

It works fine locally, it even built locally but due to some reason, it's not deploying in vercel.

**Comment by vickystickz** [comment]
I tried to check the building process on vercel but I have no access.

**Comment by jeafreezy** [comment]
![image](https://github.com/gisfest/gisfest-conference-website/assets/36086324/4a8d3ebe-b882-4739-b500-375f52d368da)


This is the error log

**Comment by jeafreezy** [comment]
Pretty annoying because it builds locally.

**Comment by jeafreezy** [comment]
I fixed this by removing all component imports in the mdx file and switched to the MDXProvider to style the contents.
